name: Run Headless Tests

on:
  workflow_call:
  workflow_dispatch:
  pull_request:

env:
  WASP_TELEMETRY_DISABLE: 1

defaults:
  run:
    shell: bash
    working-directory: headless-tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Run Headless Tests
    runs-on: ubuntu-22.04

    steps:
      - uses: "actions/checkout@v4"
        with:
          # Workaround for a Github Checkout action bug
          # https://github.com/actions/checkout/issues/1359#issuecomment-1567902034
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Verify Node
        run: |
          node --version
          npm --version

      - name: Set up Wasp
        id: setup-wasp
        run: |
          curl -sSL https://get.wasp.sh/installer.sh | sh

      - name: Verify Wasp
        run: |
          wasp version

      - name: Set up Wasp App Runner
        uses: wasp-lang/runner-action@main

      - name: Verify Wasp App Runner
        run: |
          run-wasp-app --version

      - name: Install Dependencies
        id: headless-install-dependencies
        run: |
          npm ci

      - name: Store Playwright's Version
        id: headless-store-playwright-version
        run: |
          PLAYWRIGHT_VERSION=$(npm ls @playwright/test | grep @playwright | sed 's/.*@//')
          echo "Playwright's Version: $PLAYWRIGHT_VERSION"
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

      - name: Cache Playwright Browsers for Playwright's Version
        id: headless-cache-playwright-browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}

      - name: Setup Playwright
        id: headless-setup-playwright
        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
        run: |
          npx playwright install --with-deps

      - name: Run Playwright Tests
        id: headless-run-playwright-tests-dev
        # Useful for debugging when the playwright webserver fails.
        # env:
        #   DEBUG: pw:webserver
        run: |
          npm run test
